### ISSUE TITLE
NewLoop中make的chan一直不会释放，即使runtime free了也不会，占用内存比较多

### ISSUE THREAD

**Issue by caobingsheng** [buke/quickjs-go#105]

**Comment by buke** [comment]
提交了一个pr， [https://github.com/buke/quickjs-go/pull/106](https://github.com/buke/quickjs-go/pull/106) ，你可以测试下～

**Comment by buke** [comment]
暂标记为完成，如有问题请重新打开

**Comment by caobingsheng** [comment]
抱歉最近比较忙，要是频繁创建runtime然后执行完释放还是存在内存占用，如果循环里对它压测内存会一直飙升，而且不会降低，我用pprof统计的inuse_space，不知道这个工具是不是这样用，我是个go语言新手，对内存泄漏方面还不是很在行

**Comment by buke** [comment]
能否贴一下你的测试代码？

**Comment by caobingsheng** [comment]
代码放这里了[code](https://gist.github.com/caobingsheng/ea15dabf1ff3743a745d2427f93c5859)
发现在不用polyfill和ExecuteAllPendingJobs的时候内存不会增长的很快，用了就暴增

**Comment by buke** [comment]
原实现的loop 非常简陋，现已改为使用quickjs os 内置的js_std_loop ，并导入了setTimeout / clearTimeout 。

[https://github.com/buke/quickjs-go/pull/131/files](https://github.com/buke/quickjs-go/pull/131/files)
