### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by 72wo** [buke/quickjs-go#162]
D:/c/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: Dwarf Error: Can't find .debug_ranges section.
D:/Users/111/go/pkg/mod/github.com/buke/quickjs-go@v0.4.3/deps/libs/windows_amd64/libquickjs.a(quickjs-libc.nolto.o):quickjs-libc.c:(.text+0x2c5e): undefined reference to `__imp___p__environ

**Comment by buke** [comment]
请告知环境信息及重现步骤

**Comment by buke** [comment]
windows 静态库基于mingw 12.2.0 编译，请确认你的go version > 1.20.0

**Comment by buke** [comment]
详细构建步骤，请参考 https://github.com/buke/quickjs-go/issues/151#issuecomment-2134307728

**Comment by buke** [comment]
准备关闭此讨论，如果有任何问题，请重新打开。
