### ISSUE TITLE
Is it possible to write a file?

### ISSUE THREAD

**Issue by jcchavezs** [buke/quickjs-go#163]
Is it possible to write a file or import the std library?

**Comment by buke** [comment]
this module just a js interpreter , if you want write a file , you can bind an golang  function . eg: https://github.com/buke/quickjs-go/blob/b1c165c8c112ba3cfa246484b501d0d44534f629/quickjs_test.go#L35

**Comment by buke** [comment]
I'm going to close this, if you have any question please feel free to reopen it. thanks
