### ISSUE TITLE
'setTimeout' is not defined

### ISSUE THREAD

**Issue by 456vv** [buke/quickjs-go#18]
Need support for setTimeout

**Comment by buke** [comment]
yeah, in progress. maybe a week later

**Comment by buke** [comment]
setTimeout() assumes concurrent execution of code which requires an execution environment, for example an event loop similar to nodejs or a browser.

There is a [separate project: quickjs-go-polyfill](https://github.com/buke/quickjs-go-polyfill) aimed at providing some NodeJS functionality, and it includes an event loop.
