### ISSUE TITLE
是否有计划实现 `JS_NewArrayBuffer` `JS_NewArrayBufferCopy` 等相关接口绑定

### ISSUE THREAD

**Issue by uglyer** [buke/quickjs-go#26]
想要实现 fetch 的 arrayBuffer 和 blob ,  发现没有进行绑定，是否有计划实现，或者是否接受 pr

**Comment by buke** [comment]
短期内不太有空，欢迎提交pr ～ （麻烦附上相关测试用例，现在的测试覆盖率不能再降了 :) )

这里有一个简单的 fetch https://github.com/buke/quickjs-go-polyfill 实现了response.text() 和 r response.json()，供参考 ～

**Comment by uglyer** [comment]
非常感谢，我近期会尝试一下~

**Comment by buke** [comment]
请查看 https://github.com/buke/quickjs-go/pull/40 ，感谢 @aoliaoaoaojiao 的PR。
