### ISSUE TITLE
import error : SyntaxError: expecting '('

### ISSUE THREAD

**Issue by gyf19** [buke/quickjs-go#28]
// hello.js
function hello() {
  return 'hello'
}
export default hello

//mian.go
package main

import (
	"fmt"
	"time"

	"github.com/buke/quickjs-go"
	polyfill "github.com/buke/quickjs-go-polyfill"
)

func main() {
	// Create a new runtime
	rt := quickjs.NewRuntime()
	defer rt.Close()
	// Create a new context
	ctx := rt.NewContext()
	defer ctx.Close()
	// Inject polyfills to the context
	polyfill.InjectAll(ctx)
	ret, err := ctx.Eval(``
		console.log("aaaa");
		import {hello} from './hello';
		console.log("22222"+hello())
	``)
	defer ret.Free()
	fmt.Println("error:", ret, err)
	// Wait for the timeout to finish
	time.Sleep(time.Millisecond * 100)
	rt.ExecuteAllPendingJobs()
	// Output:
	// error:  SyntaxError: expecting '('
}

**Comment by gyf19** [comment]
@buke   求助大神

**Comment by buke** [comment]
The js import statement is not implemented, please use bundle tools such as esbuild/webpack to bundle it before executing it.

未实现js import 语句，请使用 esbuild/webpack等工具打包后再执行。

**Comment by buke** [comment]
请先用esbuild 工具打包编译后，再调用quickjs 执行。



--------------------------------------------------------
Brian Wang 王步科
WeChat: buke_wang
Mobile: +86 136 0000 4025
Email: ***@***.***


gyf19 ***@***.***> 于2022年11月21日周一 14:20写道：
