### ISSUE TITLE
Support for JS_SetInterruptHandler

### ISSUE THREAD

**Issue by markandrus** [buke/quickjs-go#29]
Can we have support for `JS_SetInterruptHandler`? I would like to use it to enforce a timeout.

**Comment by buke** [comment]
yes, in this PR  https://github.com/buke/quickjs-go/pull/43 

and example is here https://github.com/buke/quickjs-go/blob/74da1156e5133f75fb2a2cfb9f65079ff08c4226/quickjs_test.go#L660

**Comment by buke** [comment]
this pr will be close . if you have any problem, feel free reopen it
