### ISSUE TITLE
Create a module that can be imported

### ISSUE THREAD

**Issue by Marcisbee** [buke/quickjs-go#304]
Hey, is there any way to create a module that can be used in `await import("foo")`?

Currently this returns: `ReferenceError: could not load module 'foo'`

Since it is possible to use dynamic import function here, I think it makes sense to allow to define module to be imported too.

For example [quickjs-emscripten](https://github.com/justjake/quickjs-emscripten) has nice api for this:
```ts
runtime.setModuleLoader((moduleName) => `export default '${moduleName}'`)
```

I think quickjs-go could use a similar api for this.

**Comment by aoliaoaoaojiao** [comment]
Hey, I studied QuickJS Warp for a while, and I've basically implemented the module functionality. You can refer to this:https://github.com/Maxwellism/gopher-qjs

**Comment by buke** [comment]
the quickjs C expose two kind of api : 
1.  /* C module definition */ in [quickjs.h](https://github.com/bellard/quickjs/blob/36911f0d3ab1a4c190a4d5cbe7c2db225a455389/quickjs.h#L1064), it allow define an new module by c api
```
typedef int JSModuleInitFunc(JSContext *ctx, JSModuleDef *m);

JSModuleDef *JS_NewCModule(JSContext *ctx, const char *name_str,
                           JSModuleInitFunc *func);
/* can only be called before the module is instantiated */
int JS_AddModuleExport(JSContext *ctx, JSModuleDef *m, const char *name_str);
int JS_AddModuleExportList(JSContext *ctx, JSModuleDef *m,
                           const JSCFunctionListEntry *tab, int len);
/* can only be called after the module is instantiated */
int JS_SetModuleExport(JSContext *ctx, JSModuleDef *m, const char *export_name,
                       JSValue val);
int JS_SetModuleExportList(JSContext *ctx, JSModuleDef *m,
                           const JSCFunctionListEntry *tab, int len);

```

2. js_module_loader in [quicks-libc.h](https://github.com/bellard/quickjs/blob/36911f0d3ab1a4c190a4d5cbe7c2db225a455389/quickjs-libc.h#L47) , it allow load es6 module from file
```
JSModuleDef *js_module_loader(JSContext *ctx,
                              const char *module_name, void *opaque);

```

First I will expose the above api, then I will think about how to package it（thanks @aoliaoaoaojiao )

**Comment by buke** [comment]
>  js_module_loader in [quicks-libc.h](https://github.com/bellard/quickjs/blob/36911f0d3ab1a4c190a4d5cbe7c2db225a455389/quickjs-libc.h#L47) , it allow load es6 module from file


load es6 module from script or file done, pls check it  https://github.com/buke/quickjs-go/commit/5fae7cb97abf0e56fa792889496a688c58c6b3f3

**Comment by Marcisbee** [comment]
@buke This is well nice 👍 Is there any way to load module as bytecode?

**Comment by buke** [comment]
yeah, I add an function LoadModuleBytecode in https://github.com/buke/quickjs-go/commit/de4baefb71d37d84d01055fcaed2684a2ac408f5

use sample:
```go
// load module from bytecode
	buf, err := ctx.CompileFile("./test/fib_module.js")
	require.NoError(t, err)

	r4, err := ctx.LoadModuleBytecode(buf, "fib_foo")
	defer r4.Free()
	require.NoError(t, err)

	r5, err := ctx.Eval(`
	import {fib} from 'fib_foo';
	globalThis.result = fib(12);
	`)
	defer r5.Free()
	require.NoError(t, err)

	require.EqualValues(t, 144, ctx.Globals().Get("result").Int32())
```

**Comment by Marcisbee** [comment]
This is so good! Thanks! 🥳 Will close this as it solves the question 👍🏼
