### ISSUE TITLE
在 ctx.Eval 时偶现错误 "at <input>:1"

### ISSUE THREAD

**Issue by zaaksam** [buke/quickjs-go#347]
运行下面的代码时，会偶现 err 为 `at <input>:1` 的错误，但重试几下又可以。

render, err := ctx.Eval(";var renderResult;ssrRender('" + urlPath + "').then((html)=>{renderResult=html;})")
if err != nil {
  return
}
defer render.Free()
ctx.Loop()

我有尝试过 ssrRender 的处理逻辑为简单的响应字符串，也是会偶现这个错误

**Comment by buke** [comment]
请注意 quickjs context 并非线程安全，对于偶发性的错误，首先排除是否运行在多线程环境。请参考 https://github.com/buke/quickjs-go/issues/342

**Comment by zaaksam** [comment]
那个 issue 我有看到，也了解了后面要改造适应多线程访问的情况。但目前还在本地调试开发阶段，页面单次刷新访问应该不存在这个问题吧。

**Comment by buke** [comment]
由于go的调度机制，即使是本地开发调试，也不会确保ctx是同一个线程中执行。如果是在web框架中使用，请在每次请求都新建 runtime 和 ctx，或者池化处理。

**Comment by zaaksam** [comment]
哦，明白，我去改造试一下

**Comment by zaaksam** [comment]
工作池处理后，没有再发生类似的问题，后续有问题我再重新打开 issue，感谢
