### ISSUE TITLE
How a initial a class instance?

### ISSUE THREAD

**Issue by yunfan** [buke/quickjs-go#349]
as above

i had tried to using  `Context.Call` and  (`LoadModuleFile` then Context.Invoke) , neither works

so could you please gave a demo for this purpose?

**Comment by buke** [comment]
pls see  https://github.com/buke/quickjs-go/blob/be74e6c1f3e2e270e833ae48a634178be1ade7ad/quickjs_test.go#L858

``` go
func TestClassConstructor(t *testing.T) {
	rt := quickjs.NewRuntime()
	defer rt.Close()
	ctx := rt.NewContext()
	defer ctx.Close()

	ret, err := ctx.Eval(`
		class Foo {
			x = 0;	
			constructor(x) {
				this.x = x;
			}
		}
		globalThis.Foo = Foo;
	`)
	defer ret.Free()
	require.NoError(t, err)

	Foo := ctx.Globals().Get("Foo")
	defer Foo.Free()

	fooInstance := Foo.New(ctx.Int32(10))
	defer fooInstance.Free()

	x := fooInstance.Get("x")
	defer x.Free()

	require.EqualValues(t, 10, x.Int32())

}
```

in https://github.com/buke/quickjs-go/releases/tag/v0.4.15

**Comment by yunfan** [comment]
that works perfect, and exactly just what i expect

btw, can i add you in wechat ? i am working on a project using quickjs-go. and i had lots of questions

**Comment by buke** [comment]
sure . you can sent me an email, and I will sent my wechat to you.

**Comment by wildfire810** [comment]
你好，我是他同事。感谢你的支持，项目非常优秀。
