### ISSUE TITLE
我想调用class实例的成员函数和class的static函数，请问应该如何处理？

### ISSUE THREAD

**Issue by wildfire810** [buke/quickjs-go#352]
如题
我想调用class实例的成员函数和class的static函数，请问应该如何处理？

**Comment by wildfire810** [comment]
我看到对象有Call函数。
那么确认一下，就是说拿到一个class的实例可以调用call，拿到class可以调用静态函数，是这样吗？

**Comment by buke** [comment]
> 我看到对象有Call函数。 那么确认一下，就是说拿到一个class的实例可以调用call，拿到class可以调用静态函数，是这样吗？

是
