### ISSUE TITLE
增加debug分支并更改cgo构建目标以用于支持debug？

### ISSUE THREAD

**Issue by aoliaoaoaojiao** [buke/quickjs-go#42]
如果需要支持debug，原始的quickjs源码并不支持，找了下 https://github.com/koush/quickjs 这个是支持的，但是或许需要更改构建目标？

**Comment by buke** [comment]
你可以先尝试在本地编译一下，可参考 https://github.com/buke/quickjs-go/blob/main/.github/workflows/build.yml
